# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "IlTempe"
description: > # this means to ignore newlines until "email:"
   io, me e tutto quello che vi posso dire

email: mtempestini@gmail.com
#blog logo
logo: "/assets/images/author.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Matteo Tempestini'
author: 'Matteo Tempestini'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://iltempe.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@il_tempe'

#fill in disqus shortname to use disqus
disqus: iltempe

google_analytics: UA-47474515-2

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/il_tempe
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	telegram
    url:	https://t.me/iltempe
    desc: Follow me on Telegram
    share_url:
    share_title:
    share_link:

  - icon:	facebook
    url:	https://www.facebook.com/matteotempestin/
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/iltempe
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

# uncomment, if you prefer to generate named folders
#page_gen-dirs: true

#page_gen:
#  - data: 'musei'
#    template: 'musei'
#    name: 'id'
#    dir: 'musei'

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

